version: '3.8'

services:
  # Frontend development service
  frontend-dev:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - app-network
    restart: unless-stopped

  # Backend development service
  backend-dev:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
      - /app/dist
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
